CREATE INDEX IDX_BETS_DAY_USER 			ON BETS	(PLACED_AT, USER_ID);
CREATE INDEX IDX_BETS_DAY_USER_AMOUNT	ON BETS	(PLACED_AT, USER_ID, AMOUNT);
CREATE INDEX IDX_BETS_PLACED_AT 		ON BETS (PLACED_AT);
CREATE INDEX IDX_BETS_PLACED_AT_STATUS 	ON BETS (PLACED_AT, STATUS);
CREATE INDEX IDX_BETS_STATUS_EVENTID 	ON BETS	(STATUS, EVENT_ID);
CREATE INDEX IDX_EVENTS_STARTTIME 		ON EVENTS(START_TIME);
CREATE INDEX idx_bets_placed_at_partial ON bets(placed_at)	WHERE placed_at >= '2025-10-15'; 
-- Erro por conta do campo IMUTAVEL
-- CREATE INDEX IDX_BETS_PLACED_AT_DAY 	ON BETS (PLACED_AT) WHERE PLACED_AT >= CURRENT_DATE - INTERVAL '7 DAY';
CREATE INDEX idx_bets_placed_status 	ON bets(placed_at, status);